openapi: 3.0.0
info:
  title: Payloop API
  version: 1.0.0
servers:
  - url: /api
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - OK
  /subscriptions:
    post:
      summary: Create a subscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSubscriptionRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSubscriptionResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The error message
  /subscriptions/{id}:
    get:
      summary: Get a subscription bu id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the subscription to get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The error message
components:
  schemas:
    Subscription:
      type: object
      properties:
        org_id:
          type: string
        id:
          type: string
        order_id:
          type: string
        customer_id:
          type: string
        status:
          type: string
        payment_method_id:
          type: string
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
          nullable: true
        billing_interval:
          type: string
        billing_interval_qty:
          type: integer
        cycles:
          type: integer
        billing_anchor:
          type: integer
        trial_ends_at:
          type: string
          format: date-time
          nullable: true
        cancel_at:
          type: string
          format: date-time
          nullable: true
        ends_at:
          type: string
          format: date-time
        last_charge:
          type: string
          format: date-time
        renews_at:
          type: string
          format: date-time
        current_period_start:
          type: string
          format: date-time
        current_period_end:
          type: string
          format: date-time
        retries:
          type: integer
        next_retry:
          type: string
          format: date-time
          nullable: true
        currency:
          type: string
        amount:
          type: integer
        metadata:
          type: object
          nullable: true
        cycles_processed:
          type: integer
        total_revenue:
          type: integer
        cancelled_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time





    CreateSubscriptionRequest:
      type: object
      properties:
        planId:
          type: string
          description: The ID of the plan to subscribe to
        customerId:
          type: string
          description: The ID of the customer to subscribe
    CreateSubscriptionResponse:
      type: object
      properties:
        subscriptionId:
          type: string
          description: The ID of the created subscription
