// Code generated by ogen, DO NOT EDIT.
package apigen

type ActivatePaymentTokenRes interface {
	activatePaymentTokenRes()
}

type AddProductToCartRes interface {
	addProductToCartRes()
}

type ArchiveProductRes interface {
	archiveProductRes()
}

type CancelSubscriptionRes interface {
	cancelSubscriptionRes()
}

type CompleteOrderRes interface {
	completeOrderRes()
}

type CreateApiKeyRes interface {
	createApiKeyRes()
}

type CreateCouponCodeRes interface {
	createCouponCodeRes()
}

type CreateCouponRes interface {
	createCouponRes()
}

type CreateCustomerPaymentMethodRes interface {
	createCustomerPaymentMethodRes()
}

type CreateCustomerRes interface {
	createCustomerRes()
}

type CreateDunningConfigurationRes interface {
	createDunningConfigurationRes()
}

type CreateGatewayRes interface {
	createGatewayRes()
}

type CreateMeterRes interface {
	createMeterRes()
}

type CreateOrderRes interface {
	createOrderRes()
}

type CreateOrganizationRes interface {
	createOrganizationRes()
}

type CreatePaymentTokenRes interface {
	createPaymentTokenRes()
}

type CreatePriceRes interface {
	createPriceRes()
}

type CreateProductRes interface {
	createProductRes()
}

type CreateProductVariantRes interface {
	createProductVariantRes()
}

type CreateSessionRes interface {
	createSessionRes()
}

type CreateSettingRes interface {
	createSettingRes()
}

type CreateWebhookSubscriptionRes interface {
	createWebhookSubscriptionRes()
}

type DeleteApiKeyRes interface {
	deleteApiKeyRes()
}

type DeleteCouponRes interface {
	deleteCouponRes()
}

type DeletePriceRes interface {
	deletePriceRes()
}

type DeleteProductRes interface {
	deleteProductRes()
}

type DeleteSettingRes interface {
	deleteSettingRes()
}

type DeleteVariantRes interface {
	deleteVariantRes()
}

type GetCouponRes interface {
	getCouponRes()
}

type GetCustomerDunningHistoryRes interface {
	getCustomerDunningHistoryRes()
}

type GetCustomerRes interface {
	getCustomerRes()
}

type GetDiscountRes interface {
	getDiscountRes()
}

type GetDunningCampaignRes interface {
	getDunningCampaignRes()
}

type GetDunningConfigurationRes interface {
	getDunningConfigurationRes()
}

type GetHealthRes interface {
	getHealthRes()
}

type GetInvoiceRes interface {
	getInvoiceRes()
}

type GetMeterRes interface {
	getMeterRes()
}

type GetOrderRes interface {
	getOrderRes()
}

type GetPaymentMethodRes interface {
	getPaymentMethodRes()
}

type GetPaymentRes interface {
	getPaymentRes()
}

type GetPriceRes interface {
	getPriceRes()
}

type GetProductRes interface {
	getProductRes()
}

type GetReminderConfigRes interface {
	getReminderConfigRes()
}

type GetSettingRes interface {
	getSettingRes()
}

type GetSubscriptionRes interface {
	getSubscriptionRes()
}

type GetSubscriptionUsageRes interface {
	getSubscriptionUsageRes()
}

type GetVariantRes interface {
	getVariantRes()
}

type IngestUsageEventsRes interface {
	ingestUsageEventsRes()
}

type ListApiKeysRes interface {
	listApiKeysRes()
}

type ListCouponCodesRes interface {
	listCouponCodesRes()
}

type ListCouponsRes interface {
	listCouponsRes()
}

type ListCustomersRes interface {
	listCustomersRes()
}

type ListDunningCampaignAttemptsRes interface {
	listDunningCampaignAttemptsRes()
}

type ListDunningCampaignCommunicationsRes interface {
	listDunningCampaignCommunicationsRes()
}

type ListDunningCampaignsRes interface {
	listDunningCampaignsRes()
}

type ListDunningConfigurationsRes interface {
	listDunningConfigurationsRes()
}

type ListInvoicesRes interface {
	listInvoicesRes()
}

type ListMetersRes interface {
	listMetersRes()
}

type ListOrderSubscriptionsRes interface {
	listOrderSubscriptionsRes()
}

type ListOrdersRes interface {
	listOrdersRes()
}

type ListPaymentsRes interface {
	listPaymentsRes()
}

type ListProductVariantsRes interface {
	listProductVariantsRes()
}

type ListProductsRes interface {
	listProductsRes()
}

type ListSettingsRes interface {
	listSettingsRes()
}

type ListSubscriptionInvoicesRes interface {
	listSubscriptionInvoicesRes()
}

type ListSubscriptionPaymentsRes interface {
	listSubscriptionPaymentsRes()
}

type ListSubscriptionsRes interface {
	listSubscriptionsRes()
}

type ListVariantPricesRes interface {
	listVariantPricesRes()
}

type ListWebhookSubscriptionsRes interface {
	listWebhookSubscriptionsRes()
}

type PauseSubscriptionRes interface {
	pauseSubscriptionRes()
}

type ReceiveWebhookRes interface {
	receiveWebhookRes()
}

type RemoveItemFromCartRes interface {
	removeItemFromCartRes()
}

type ResumeSubscriptionRes interface {
	resumeSubscriptionRes()
}

type TriggerDunningManualAttemptRes interface {
	triggerDunningManualAttemptRes()
}

type UnarchiveProductRes interface {
	unarchiveProductRes()
}

type UpdateCouponCodeRes interface {
	updateCouponCodeRes()
}

type UpdateCouponRes interface {
	updateCouponRes()
}

type UpdateCustomerPaymentMethodRes interface {
	updateCustomerPaymentMethodRes()
}

type UpdateDunningCampaignRes interface {
	updateDunningCampaignRes()
}

type UpdateDunningConfigurationRes interface {
	updateDunningConfigurationRes()
}

type UpdatePriceRes interface {
	updatePriceRes()
}

type UpdateProductRes interface {
	updateProductRes()
}

type UpdateReminderConfigRes interface {
	updateReminderConfigRes()
}

type UpdateSettingRes interface {
	updateSettingRes()
}

type UpdateSubscriptionBillingAnchorRes interface {
	updateSubscriptionBillingAnchorRes()
}

type UpdateSubscriptionRes interface {
	updateSubscriptionRes()
}

type UpdateVariantRes interface {
	updateVariantRes()
}

type VerifyPaymentTokenRes interface {
	verifyPaymentTokenRes()
}
