// Code generated by ogen, DO NOT EDIT.

package apigen

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleApiKeyAuth handles apiKeyAuth security.
	// Organization API key, sent as the `x-api-key` header. Used by the CLI and programmatic clients.
	HandleApiKeyAuth(ctx context.Context, operationName OperationName, t ApiKeyAuth) (context.Context, error)
	// HandleBearerAuth handles bearerAuth security.
	// Clerk session JWT, sent as `Authorization: Bearer <token>`. Used by the dashboard.
	HandleBearerAuth(ctx context.Context, operationName OperationName, t BearerAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesApiKeyAuth is a private map storing roles per operation.
var operationRolesApiKeyAuth = map[string][]string{
	ActivatePaymentTokenOperation:              []string{},
	AddProductToCartOperation:                  []string{},
	ArchiveProductOperation:                    []string{},
	CancelSubscriptionOperation:                []string{},
	CompleteOrderOperation:                     []string{},
	CreateApiKeyOperation:                      []string{},
	CreateCouponOperation:                      []string{},
	CreateCouponCodeOperation:                  []string{},
	CreateCustomerOperation:                    []string{},
	CreateCustomerPaymentMethodOperation:       []string{},
	CreateDunningConfigurationOperation:        []string{},
	CreateGatewayOperation:                     []string{},
	CreateMeterOperation:                       []string{},
	CreateOrderOperation:                       []string{},
	CreateOrganizationOperation:                []string{},
	CreatePaymentTokenOperation:                []string{},
	CreatePriceOperation:                       []string{},
	CreateProductOperation:                     []string{},
	CreateProductVariantOperation:              []string{},
	CreateSessionOperation:                     []string{},
	CreateSettingOperation:                     []string{},
	CreateWebhookSubscriptionOperation:         []string{},
	DeleteApiKeyOperation:                      []string{},
	DeleteCouponOperation:                      []string{},
	DeletePriceOperation:                       []string{},
	DeleteProductOperation:                     []string{},
	DeleteSettingOperation:                     []string{},
	DeleteVariantOperation:                     []string{},
	GetCouponOperation:                         []string{},
	GetCustomerOperation:                       []string{},
	GetCustomerDunningHistoryOperation:         []string{},
	GetDiscountOperation:                       []string{},
	GetDunningCampaignOperation:                []string{},
	GetDunningConfigurationOperation:           []string{},
	GetInvoiceOperation:                        []string{},
	GetMeterOperation:                          []string{},
	GetOrderOperation:                          []string{},
	GetPaymentOperation:                        []string{},
	GetPaymentMethodOperation:                  []string{},
	GetPriceOperation:                          []string{},
	GetProductOperation:                        []string{},
	GetReminderConfigOperation:                 []string{},
	GetSettingOperation:                        []string{},
	GetSubscriptionOperation:                   []string{},
	GetSubscriptionUsageOperation:              []string{},
	GetVariantOperation:                        []string{},
	IngestUsageEventsOperation:                 []string{},
	ListApiKeysOperation:                       []string{},
	ListCouponCodesOperation:                   []string{},
	ListCouponsOperation:                       []string{},
	ListCustomersOperation:                     []string{},
	ListDunningCampaignAttemptsOperation:       []string{},
	ListDunningCampaignCommunicationsOperation: []string{},
	ListDunningCampaignsOperation:              []string{},
	ListDunningConfigurationsOperation:         []string{},
	ListInvoicesOperation:                      []string{},
	ListMetersOperation:                        []string{},
	ListOrderSubscriptionsOperation:            []string{},
	ListOrdersOperation:                        []string{},
	ListPaymentsOperation:                      []string{},
	ListProductVariantsOperation:               []string{},
	ListProductsOperation:                      []string{},
	ListSettingsOperation:                      []string{},
	ListSubscriptionInvoicesOperation:          []string{},
	ListSubscriptionPaymentsOperation:          []string{},
	ListSubscriptionsOperation:                 []string{},
	ListVariantPricesOperation:                 []string{},
	ListWebhookSubscriptionsOperation:          []string{},
	PauseSubscriptionOperation:                 []string{},
	PayOrderOperation:                          []string{},
	RemoveItemFromCartOperation:                []string{},
	ResumeSubscriptionOperation:                []string{},
	TriggerDunningManualAttemptOperation:       []string{},
	UnarchiveProductOperation:                  []string{},
	UpdateCouponOperation:                      []string{},
	UpdateCouponCodeOperation:                  []string{},
	UpdateCustomerPaymentMethodOperation:       []string{},
	UpdateDunningCampaignOperation:             []string{},
	UpdateDunningConfigurationOperation:        []string{},
	UpdatePriceOperation:                       []string{},
	UpdateProductOperation:                     []string{},
	UpdateReminderConfigOperation:              []string{},
	UpdateSettingOperation:                     []string{},
	UpdateSubscriptionOperation:                []string{},
	UpdateSubscriptionBillingAnchorOperation:   []string{},
	UpdateVariantOperation:                     []string{},
	VerifyPaymentTokenOperation:                []string{},
}

// GetRolesForApiKeyAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForApiKeyAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForApiKeyAuth(operation string) []string {
	roles, ok := operationRolesApiKeyAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesBearerAuth is a private map storing roles per operation.
var operationRolesBearerAuth = map[string][]string{
	ActivatePaymentTokenOperation:              []string{},
	AddProductToCartOperation:                  []string{},
	ArchiveProductOperation:                    []string{},
	CancelSubscriptionOperation:                []string{},
	CompleteOrderOperation:                     []string{},
	CreateApiKeyOperation:                      []string{},
	CreateCouponOperation:                      []string{},
	CreateCouponCodeOperation:                  []string{},
	CreateCustomerOperation:                    []string{},
	CreateCustomerPaymentMethodOperation:       []string{},
	CreateDunningConfigurationOperation:        []string{},
	CreateGatewayOperation:                     []string{},
	CreateMeterOperation:                       []string{},
	CreateOrderOperation:                       []string{},
	CreateOrganizationOperation:                []string{},
	CreatePaymentTokenOperation:                []string{},
	CreatePriceOperation:                       []string{},
	CreateProductOperation:                     []string{},
	CreateProductVariantOperation:              []string{},
	CreateSessionOperation:                     []string{},
	CreateSettingOperation:                     []string{},
	CreateWebhookSubscriptionOperation:         []string{},
	DeleteApiKeyOperation:                      []string{},
	DeleteCouponOperation:                      []string{},
	DeletePriceOperation:                       []string{},
	DeleteProductOperation:                     []string{},
	DeleteSettingOperation:                     []string{},
	DeleteVariantOperation:                     []string{},
	GetCouponOperation:                         []string{},
	GetCustomerOperation:                       []string{},
	GetCustomerDunningHistoryOperation:         []string{},
	GetDiscountOperation:                       []string{},
	GetDunningCampaignOperation:                []string{},
	GetDunningConfigurationOperation:           []string{},
	GetInvoiceOperation:                        []string{},
	GetMeterOperation:                          []string{},
	GetOrderOperation:                          []string{},
	GetPaymentOperation:                        []string{},
	GetPaymentMethodOperation:                  []string{},
	GetPriceOperation:                          []string{},
	GetProductOperation:                        []string{},
	GetReminderConfigOperation:                 []string{},
	GetSettingOperation:                        []string{},
	GetSubscriptionOperation:                   []string{},
	GetSubscriptionUsageOperation:              []string{},
	GetVariantOperation:                        []string{},
	IngestUsageEventsOperation:                 []string{},
	ListApiKeysOperation:                       []string{},
	ListCouponCodesOperation:                   []string{},
	ListCouponsOperation:                       []string{},
	ListCustomersOperation:                     []string{},
	ListDunningCampaignAttemptsOperation:       []string{},
	ListDunningCampaignCommunicationsOperation: []string{},
	ListDunningCampaignsOperation:              []string{},
	ListDunningConfigurationsOperation:         []string{},
	ListInvoicesOperation:                      []string{},
	ListMetersOperation:                        []string{},
	ListOrderSubscriptionsOperation:            []string{},
	ListOrdersOperation:                        []string{},
	ListPaymentsOperation:                      []string{},
	ListProductVariantsOperation:               []string{},
	ListProductsOperation:                      []string{},
	ListSettingsOperation:                      []string{},
	ListSubscriptionInvoicesOperation:          []string{},
	ListSubscriptionPaymentsOperation:          []string{},
	ListSubscriptionsOperation:                 []string{},
	ListVariantPricesOperation:                 []string{},
	ListWebhookSubscriptionsOperation:          []string{},
	PauseSubscriptionOperation:                 []string{},
	PayOrderOperation:                          []string{},
	RemoveItemFromCartOperation:                []string{},
	ResumeSubscriptionOperation:                []string{},
	TriggerDunningManualAttemptOperation:       []string{},
	UnarchiveProductOperation:                  []string{},
	UpdateCouponOperation:                      []string{},
	UpdateCouponCodeOperation:                  []string{},
	UpdateCustomerPaymentMethodOperation:       []string{},
	UpdateDunningCampaignOperation:             []string{},
	UpdateDunningConfigurationOperation:        []string{},
	UpdatePriceOperation:                       []string{},
	UpdateProductOperation:                     []string{},
	UpdateReminderConfigOperation:              []string{},
	UpdateSettingOperation:                     []string{},
	UpdateSubscriptionOperation:                []string{},
	UpdateSubscriptionBillingAnchorOperation:   []string{},
	UpdateVariantOperation:                     []string{},
	VerifyPaymentTokenOperation:                []string{},
}

// GetRolesForBearerAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerAuth(operation string) []string {
	roles, ok := operationRolesBearerAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityApiKeyAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t ApiKeyAuth
	const parameterName = "x-api-key"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesApiKeyAuth[operationName]
	rctx, err := s.sec.HandleApiKeyAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BearerAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearerAuth[operationName]
	rctx, err := s.sec.HandleBearerAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// ApiKeyAuth provides apiKeyAuth security value.
	// Organization API key, sent as the `x-api-key` header. Used by the CLI and programmatic clients.
	ApiKeyAuth(ctx context.Context, operationName OperationName) (ApiKeyAuth, error)
	// BearerAuth provides bearerAuth security value.
	// Clerk session JWT, sent as `Authorization: Bearer <token>`. Used by the dashboard.
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
}

func (s *Client) securityApiKeyAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ApiKeyAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ApiKeyAuth\"")
	}
	req.Header.Set("x-api-key", t.APIKey)
	return nil
}
func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
