// Code generated by ogen, DO NOT EDIT.

package apigen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ActivatePaymentToken implements activatePaymentToken operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*DunningHandler).ActivatePaymentToken`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/payment-tokens/activate
func (UnimplementedHandler) ActivatePaymentToken(ctx context.Context, req *ActivatePaymentTokenRequest, params ActivatePaymentTokenParams) (r ActivatePaymentTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddProductToCart implements addProductToCart operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*CartHandler).AddProduct`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/carts/{id}/add
func (UnimplementedHandler) AddProductToCart(ctx context.Context, req *AddItemRequest, params AddProductToCartParams) (r AddProductToCartRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ArchiveProduct implements archiveProduct operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).Archive`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/products/{id}/archive
func (UnimplementedHandler) ArchiveProduct(ctx context.Context, params ArchiveProductParams) (r ArchiveProductRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CancelSubscription implements cancelSubscription operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*SubscriptionHandler).Cancel`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// PUT /api/subscriptions/{id}/cancel
func (UnimplementedHandler) CancelSubscription(ctx context.Context, req *CancelSubscriptionRequest, params CancelSubscriptionParams) (r CancelSubscriptionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CompleteOrder implements completeOrder operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*OrderHandler).CompleteOrder`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//   - `main.main.func1`
//
// POST /api/orders/{id}/complete
func (UnimplementedHandler) CompleteOrder(ctx context.Context, req *CompleteOrderRequest, params CompleteOrderParams) (r CompleteOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateApiKey implements createApiKey operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ApiKeyHandler).Create`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/api-keys
func (UnimplementedHandler) CreateApiKey(ctx context.Context, req *CreateApiKeyInput, params CreateApiKeyParams) (r CreateApiKeyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCoupon implements createCoupon operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*CouponHandler).Create`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/coupons
func (UnimplementedHandler) CreateCoupon(ctx context.Context, req *CreateCouponInput, params CreateCouponParams) (r CreateCouponRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCouponCode implements createCouponCode operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*CouponHandler).CreateCode`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/coupons/{id}/codes
func (UnimplementedHandler) CreateCouponCode(ctx context.Context, req *CreateCouponCodeInput, params CreateCouponCodeParams) (r CreateCouponCodeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCustomer implements createCustomer operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*CustomerHandler).Create`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/customers
func (UnimplementedHandler) CreateCustomer(ctx context.Context, req *CreateCustomerInput, params CreateCustomerParams) (r CreateCustomerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCustomerPaymentMethod implements createCustomerPaymentMethod operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*CustomerHandler).CreateCustomerPaymentMethod`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/customers/{id}/payment-methods
func (UnimplementedHandler) CreateCustomerPaymentMethod(ctx context.Context, req CreatePaymentMethodInput, params CreateCustomerPaymentMethodParams) (r CreateCustomerPaymentMethodRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDunningConfiguration implements createDunningConfiguration operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*DunningHandler).CreateConfiguration`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/dunning/configurations
func (UnimplementedHandler) CreateDunningConfiguration(ctx context.Context, req *CreateDunningConfigurationRequest, params CreateDunningConfigurationParams) (r CreateDunningConfigurationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateGateway implements createGateway operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*PspHandler).Create`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/gateways
func (UnimplementedHandler) CreateGateway(ctx context.Context, req *CreateGatewayRequest, params CreateGatewayParams) (r CreateGatewayRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMeter implements createMeter operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*MeterHandler).Create`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/meters
func (UnimplementedHandler) CreateMeter(ctx context.Context, req *CreateMeterRequest, params CreateMeterParams) (r CreateMeterRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrder implements createOrder operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*OrderHandler).CreateOrder`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//   - `main.main.func1`
//
// POST /api/orders
func (UnimplementedHandler) CreateOrder(ctx context.Context, req *CreateOrderRequest, params CreateOrderParams) (r CreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrganization implements createOrganization operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*OrgHandler).Create`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/organizations
func (UnimplementedHandler) CreateOrganization(ctx context.Context, req *CreateOrgRequest, params CreateOrganizationParams) (r CreateOrganizationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePaymentToken implements createPaymentToken operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*DunningHandler).CreatePaymentToken`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/admin/subscriptions/{id}/payment-tokens
func (UnimplementedHandler) CreatePaymentToken(ctx context.Context, req *CreatePaymentTokenRequest, params CreatePaymentTokenParams) (r CreatePaymentTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePrice implements createPrice operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).CreatePrice`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/prices
func (UnimplementedHandler) CreatePrice(ctx context.Context, req *CreatePriceRequest, params CreatePriceParams) (r CreatePriceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProduct implements createProduct operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).Create`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/products
func (UnimplementedHandler) CreateProduct(ctx context.Context, req *CreateProductRequest, params CreateProductParams) (r CreateProductRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProductVariant implements createProductVariant operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).CreateVariant`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/products/{id}/variants
func (UnimplementedHandler) CreateProductVariant(ctx context.Context, req *CreateVariantRequest, params CreateProductVariantParams) (r CreateProductVariantRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSession implements createSession operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*SessionHandler).Create`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/sessions
func (UnimplementedHandler) CreateSession(ctx context.Context, req *CreateSessionRequest, params CreateSessionParams) (r CreateSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSetting implements createSetting operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*SettingHandler).Create`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/settings
func (UnimplementedHandler) CreateSetting(ctx context.Context, req *CreateSettingRequest, params CreateSettingParams) (r CreateSettingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateWebhookSubscription implements createWebhookSubscription operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*WebhookSubscriptionHandler).Create`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/webhooks
func (UnimplementedHandler) CreateWebhookSubscription(ctx context.Context, req *CreateWebhookSubscriptionRequest, params CreateWebhookSubscriptionParams) (r CreateWebhookSubscriptionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteApiKey implements deleteApiKey operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ApiKeyHandler).Delete`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// DELETE /api/api-keys/{id}
func (UnimplementedHandler) DeleteApiKey(ctx context.Context, params DeleteApiKeyParams) (r DeleteApiKeyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCoupon implements deleteCoupon operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*CouponHandler).Delete`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// DELETE /api/coupons/{id}
func (UnimplementedHandler) DeleteCoupon(ctx context.Context, params DeleteCouponParams) (r DeleteCouponRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeletePrice implements deletePrice operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).DeletePrice`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// DELETE /api/prices/{priceId}
func (UnimplementedHandler) DeletePrice(ctx context.Context, params DeletePriceParams) (r DeletePriceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteProduct implements deleteProduct operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).Delete`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// DELETE /api/products/{id}
func (UnimplementedHandler) DeleteProduct(ctx context.Context, params DeleteProductParams) (r DeleteProductRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSetting implements deleteSetting operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*SettingHandler).Delete`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// DELETE /api/settings/{parentId}/{id}
func (UnimplementedHandler) DeleteSetting(ctx context.Context, params DeleteSettingParams) (r DeleteSettingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteVariant implements deleteVariant operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).DeleteVariant`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// DELETE /api/variants/{variantId}
func (UnimplementedHandler) DeleteVariant(ctx context.Context, params DeleteVariantParams) (r DeleteVariantRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCoupon implements getCoupon operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*CouponHandler).Get`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/coupons/{id}
func (UnimplementedHandler) GetCoupon(ctx context.Context, params GetCouponParams) (r GetCouponRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCustomer implements getCustomer operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*CustomerHandler).Get`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/customers/{id}
func (UnimplementedHandler) GetCustomer(ctx context.Context, params GetCustomerParams) (r GetCustomerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCustomerDunningHistory implements getCustomerDunningHistory operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*DunningHandler).GetCustomerDunningHistory`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/customers/{id}/dunning-history
func (UnimplementedHandler) GetCustomerDunningHistory(ctx context.Context, params GetCustomerDunningHistoryParams) (r GetCustomerDunningHistoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDiscount implements getDiscount operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*CouponHandler).GetDiscount`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/discounts/{id}
func (UnimplementedHandler) GetDiscount(ctx context.Context, params GetDiscountParams) (r GetDiscountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDunningCampaign implements getDunningCampaign operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*DunningHandler).GetCampaign`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/dunning/campaigns/{id}
func (UnimplementedHandler) GetDunningCampaign(ctx context.Context, params GetDunningCampaignParams) (r GetDunningCampaignRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDunningConfiguration implements getDunningConfiguration operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*DunningHandler).GetConfiguration`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/dunning/configurations/{id}
func (UnimplementedHandler) GetDunningConfiguration(ctx context.Context, params GetDunningConfigurationParams) (r GetDunningConfigurationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*HealthHandler).Healthcheck`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/health
func (UnimplementedHandler) GetHealth(ctx context.Context, params GetHealthParams) (r GetHealthRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInvoice implements getInvoice operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*InvoiceHandler).Get`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/invoices/{id}
func (UnimplementedHandler) GetInvoice(ctx context.Context, params GetInvoiceParams) (r GetInvoiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMeter implements getMeter operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*MeterHandler).Get`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/meters/{id}
func (UnimplementedHandler) GetMeter(ctx context.Context, params GetMeterParams) (r GetMeterRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrder implements getOrder operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*OrderHandler).Get`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//   - `main.main.func1`
//
// GET /api/orders/{id}
func (UnimplementedHandler) GetOrder(ctx context.Context, params GetOrderParams) (r GetOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPayment implements getPayment operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*PaymentHandler).Get`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/payments/{id}
func (UnimplementedHandler) GetPayment(ctx context.Context, params GetPaymentParams) (r GetPaymentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPaymentMethod implements getPaymentMethod operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*PaymentMethodHandler).Get`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/payment-methods/{id}
func (UnimplementedHandler) GetPaymentMethod(ctx context.Context, params GetPaymentMethodParams) (r GetPaymentMethodRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPrice implements getPrice operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).GetPrice`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/prices/{priceId}
func (UnimplementedHandler) GetPrice(ctx context.Context, params GetPriceParams) (r GetPriceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProduct implements getProduct operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).Get`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/products/{id}
func (UnimplementedHandler) GetProduct(ctx context.Context, params GetProductParams) (r GetProductRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetReminderConfig implements getReminderConfig operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ReminderConfigHandler).Get`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/billing/reminder-config
func (UnimplementedHandler) GetReminderConfig(ctx context.Context, params GetReminderConfigParams) (r GetReminderConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSetting implements getSetting operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*SettingHandler).Get`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/settings/{parentId}/{id}
func (UnimplementedHandler) GetSetting(ctx context.Context, params GetSettingParams) (r GetSettingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSubscription implements getSubscription operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*SubscriptionHandler).Get`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/subscriptions/{id}
func (UnimplementedHandler) GetSubscription(ctx context.Context, params GetSubscriptionParams) (r GetSubscriptionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSubscriptionUsage implements getSubscriptionUsage operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*UsageHandler).SubscriptionUsage`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/subscriptions/{id}/usage
func (UnimplementedHandler) GetSubscriptionUsage(ctx context.Context, params GetSubscriptionUsageParams) (r GetSubscriptionUsageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVariant implements getVariant operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).GetVariant`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/variants/{variantId}
func (UnimplementedHandler) GetVariant(ctx context.Context, params GetVariantParams) (r GetVariantRes, _ error) {
	return r, ht.ErrNotImplemented
}

// IngestUsageEvents implements ingestUsageEvents operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*UsageHandler).Ingest`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/usage/ingest
func (UnimplementedHandler) IngestUsageEvents(ctx context.Context, req *IngestEventsRequest, params IngestUsageEventsParams) (r IngestUsageEventsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListApiKeys implements listApiKeys operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ApiKeyHandler).List`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/api-keys
func (UnimplementedHandler) ListApiKeys(ctx context.Context, params ListApiKeysParams) (r ListApiKeysRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListCouponCodes implements listCouponCodes operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*CouponHandler).ListCodes`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/coupons/{id}/codes
func (UnimplementedHandler) ListCouponCodes(ctx context.Context, params ListCouponCodesParams) (r ListCouponCodesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListCoupons implements listCoupons operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*CouponHandler).List`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/coupons
func (UnimplementedHandler) ListCoupons(ctx context.Context, params ListCouponsParams) (r ListCouponsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListCustomers implements listCustomers operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*CustomerHandler).List`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/customers
func (UnimplementedHandler) ListCustomers(ctx context.Context, params ListCustomersParams) (r ListCustomersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDunningCampaignAttempts implements listDunningCampaignAttempts operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*DunningHandler).ListCampaignAttempts`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/dunning/campaigns/{id}/attempts
func (UnimplementedHandler) ListDunningCampaignAttempts(ctx context.Context, params ListDunningCampaignAttemptsParams) (r ListDunningCampaignAttemptsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDunningCampaignCommunications implements listDunningCampaignCommunications operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*DunningHandler).ListCampaignCommunications`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/dunning/campaigns/{id}/communications
func (UnimplementedHandler) ListDunningCampaignCommunications(ctx context.Context, params ListDunningCampaignCommunicationsParams) (r ListDunningCampaignCommunicationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDunningCampaigns implements listDunningCampaigns operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*DunningHandler).ListCampaigns`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/dunning/campaigns
func (UnimplementedHandler) ListDunningCampaigns(ctx context.Context, params ListDunningCampaignsParams) (r ListDunningCampaignsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDunningConfigurations implements listDunningConfigurations operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*DunningHandler).ListConfigurations`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/dunning/configurations
func (UnimplementedHandler) ListDunningConfigurations(ctx context.Context, params ListDunningConfigurationsParams) (r ListDunningConfigurationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListInvoices implements listInvoices operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*InvoiceHandler).List`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/invoices
func (UnimplementedHandler) ListInvoices(ctx context.Context, params ListInvoicesParams) (r ListInvoicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMeters implements listMeters operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*MeterHandler).List`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/meters
func (UnimplementedHandler) ListMeters(ctx context.Context, params ListMetersParams) (r ListMetersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOrderSubscriptions implements listOrderSubscriptions operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*OrderHandler).ListSubscriptions`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//   - `main.main.func1`
//
// GET /api/orders/{id}/subscriptions
func (UnimplementedHandler) ListOrderSubscriptions(ctx context.Context, params ListOrderSubscriptionsParams) (r ListOrderSubscriptionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOrders implements listOrders operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*OrderHandler).List`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//   - `main.main.func1`
//
// GET /api/orders
func (UnimplementedHandler) ListOrders(ctx context.Context, params ListOrdersParams) (r ListOrdersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPayments implements listPayments operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*PaymentHandler).List`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/payments
func (UnimplementedHandler) ListPayments(ctx context.Context, params ListPaymentsParams) (r ListPaymentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProductVariants implements listProductVariants operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).ListVariants`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/products/{id}/variants
func (UnimplementedHandler) ListProductVariants(ctx context.Context, params ListProductVariantsParams) (r ListProductVariantsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProducts implements listProducts operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).List`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/products
func (UnimplementedHandler) ListProducts(ctx context.Context, params ListProductsParams) (r ListProductsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSettings implements listSettings operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*SettingHandler).List`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/settings
func (UnimplementedHandler) ListSettings(ctx context.Context, params ListSettingsParams) (r ListSettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSubscriptionInvoices implements listSubscriptionInvoices operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*InvoiceHandler).ListBySubscription`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/subscriptions/{id}/invoices
func (UnimplementedHandler) ListSubscriptionInvoices(ctx context.Context, params ListSubscriptionInvoicesParams) (r ListSubscriptionInvoicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSubscriptionPayments implements listSubscriptionPayments operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*SubscriptionHandler).ListPayments`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/subscriptions/{id}/payments
func (UnimplementedHandler) ListSubscriptionPayments(ctx context.Context, params ListSubscriptionPaymentsParams) (r ListSubscriptionPaymentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSubscriptions implements listSubscriptions operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*SubscriptionHandler).List`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/subscriptions
func (UnimplementedHandler) ListSubscriptions(ctx context.Context, params ListSubscriptionsParams) (r ListSubscriptionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListVariantPrices implements listVariantPrices operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).ListPrices`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/variants/{variantId}/prices
func (UnimplementedHandler) ListVariantPrices(ctx context.Context, params ListVariantPricesParams) (r ListVariantPricesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListWebhookSubscriptions implements listWebhookSubscriptions operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*WebhookSubscriptionHandler).List`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// GET /api/webhooks
func (UnimplementedHandler) ListWebhookSubscriptions(ctx context.Context, params ListWebhookSubscriptionsParams) (r ListWebhookSubscriptionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PauseSubscription implements pauseSubscription operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*SubscriptionHandler).Pause`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// PUT /api/subscriptions/{id}/pause
func (UnimplementedHandler) PauseSubscription(ctx context.Context, req *PauseSubscriptionRequest, params PauseSubscriptionParams) (r PauseSubscriptionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PayOrder implements payOrder operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*OrderHandler).Pay`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//   - `main.main.func1`
//
// POST /api/orders/{id}/pay
func (UnimplementedHandler) PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (r PayOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReceiveWebhook implements receiveWebhook operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*WebhookHandler).Process`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/notify
func (UnimplementedHandler) ReceiveWebhook(ctx context.Context, params ReceiveWebhookParams) (r ReceiveWebhookRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveItemFromCart implements removeItemFromCart operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*CartHandler).RemoveItem`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/carts/{id}/remove
func (UnimplementedHandler) RemoveItemFromCart(ctx context.Context, req *RemoveItemRequest, params RemoveItemFromCartParams) (r RemoveItemFromCartRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ResumeSubscription implements resumeSubscription operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*SubscriptionHandler).Resume`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// PUT /api/subscriptions/{id}/resume
func (UnimplementedHandler) ResumeSubscription(ctx context.Context, req *ResumeSubscriptionRequest, params ResumeSubscriptionParams) (r ResumeSubscriptionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TriggerDunningManualAttempt implements triggerDunningManualAttempt operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*DunningHandler).TriggerManualAttempt`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/dunning/campaigns/{id}/attempts
func (UnimplementedHandler) TriggerDunningManualAttempt(ctx context.Context, req *TriggerManualAttemptRequest, params TriggerDunningManualAttemptParams) (r TriggerDunningManualAttemptRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UnarchiveProduct implements unarchiveProduct operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).Unarchive`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/products/{id}/unarchive
func (UnimplementedHandler) UnarchiveProduct(ctx context.Context, params UnarchiveProductParams) (r UnarchiveProductRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCoupon implements updateCoupon operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*CouponHandler).Update`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// PATCH /api/coupons/{id}
func (UnimplementedHandler) UpdateCoupon(ctx context.Context, req *UpdateCouponInput, params UpdateCouponParams) (r UpdateCouponRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCouponCode implements updateCouponCode operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*CouponHandler).UpdateCode`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// PATCH /api/coupon-codes/{id}
func (UnimplementedHandler) UpdateCouponCode(ctx context.Context, req *UpdateCouponCodeInput, params UpdateCouponCodeParams) (r UpdateCouponCodeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCustomerPaymentMethod implements updateCustomerPaymentMethod operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*CustomerHandler).UpdateCustomerPaymentMethod`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// PUT /api/customers/{id}/payment-methods/{pmid}
func (UnimplementedHandler) UpdateCustomerPaymentMethod(ctx context.Context, req UpdatePaymentMethodInput, params UpdateCustomerPaymentMethodParams) (r UpdateCustomerPaymentMethodRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDunningCampaign implements updateDunningCampaign operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*DunningHandler).UpdateCampaign`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// PATCH /api/dunning/campaigns/{id}
func (UnimplementedHandler) UpdateDunningCampaign(ctx context.Context, req *UpdateDunningCampaignRequest, params UpdateDunningCampaignParams) (r UpdateDunningCampaignRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDunningConfiguration implements updateDunningConfiguration operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*DunningHandler).UpdateConfiguration`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// PATCH /api/dunning/configurations/{id}
func (UnimplementedHandler) UpdateDunningConfiguration(ctx context.Context, req *UpdateDunningConfigurationRequest, params UpdateDunningConfigurationParams) (r UpdateDunningConfigurationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePrice implements updatePrice operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).UpdatePrice`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// PATCH /api/prices/{priceId}
func (UnimplementedHandler) UpdatePrice(ctx context.Context, req *CreatePriceRequest, params UpdatePriceParams) (r UpdatePriceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateProduct implements updateProduct operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).Update`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// PATCH /api/products/{id}
func (UnimplementedHandler) UpdateProduct(ctx context.Context, req *UpdateProductRequest, params UpdateProductParams) (r UpdateProductRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateReminderConfig implements updateReminderConfig operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ReminderConfigHandler).Put`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// PUT /api/billing/reminder-config
func (UnimplementedHandler) UpdateReminderConfig(ctx context.Context, req *ReminderConfigDTO, params UpdateReminderConfigParams) (r UpdateReminderConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSetting implements updateSetting operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*SettingHandler).Update`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// PUT /api/settings/{parentId}/{id}
func (UnimplementedHandler) UpdateSetting(ctx context.Context, req *UpdateSettingRequest, params UpdateSettingParams) (r UpdateSettingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSubscription implements updateSubscription operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*SubscriptionHandler).Update`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// PATCH /api/subscriptions/{id}
func (UnimplementedHandler) UpdateSubscription(ctx context.Context, req *UpdateSubscriptionRequest, params UpdateSubscriptionParams) (r UpdateSubscriptionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSubscriptionBillingAnchor implements updateSubscriptionBillingAnchor operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*SubscriptionHandler).UpdateBillingAnchor`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// PATCH /api/subscriptions/{id}/billing-anchor
func (UnimplementedHandler) UpdateSubscriptionBillingAnchor(ctx context.Context, req *UpdateBillingAnchorRequest, params UpdateSubscriptionBillingAnchorParams) (r UpdateSubscriptionBillingAnchorRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateVariant implements updateVariant operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*ProductHandler).UpdateVariant`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// PUT /api/variants/{variantId}
func (UnimplementedHandler) UpdateVariant(ctx context.Context, req *UpdateVariantRequest, params UpdateVariantParams) (r UpdateVariantRes, _ error) {
	return r, ht.ErrNotImplemented
}

// VerifyPaymentToken implements verifyPaymentToken operation.
//
// # Controller:
//
// `getpaidhq/internal/adapter/http.(*DunningHandler).VerifyPaymentToken`
//
// # Middlewares:
//
//   - `github.com/go-fuego/fuego.defaultLogger.middleware`
//
// POST /api/payment-tokens/verify
func (UnimplementedHandler) VerifyPaymentToken(ctx context.Context, req *VerifyPaymentTokenRequest, params VerifyPaymentTokenParams) (r VerifyPaymentTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}
