// Code generated by ogen, DO NOT EDIT.

package apigen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ActivatePaymentToken implements activatePaymentToken operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*DunningHandler).ActivatePaymentToken`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/payment-tokens/activate
	ActivatePaymentToken(ctx context.Context, req *ActivatePaymentTokenRequest, params ActivatePaymentTokenParams) (ActivatePaymentTokenRes, error)
	// AddProductToCart implements addProductToCart operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*CartHandler).AddProduct`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/carts/{id}/add
	AddProductToCart(ctx context.Context, req *AddItemRequest, params AddProductToCartParams) (AddProductToCartRes, error)
	// ArchiveProduct implements archiveProduct operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).Archive`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/products/{id}/archive
	ArchiveProduct(ctx context.Context, params ArchiveProductParams) (ArchiveProductRes, error)
	// CancelSubscription implements cancelSubscription operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*SubscriptionHandler).Cancel`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// PUT /api/subscriptions/{id}/cancel
	CancelSubscription(ctx context.Context, req *CancelSubscriptionRequest, params CancelSubscriptionParams) (CancelSubscriptionRes, error)
	// CompleteOrder implements completeOrder operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*OrderHandler).CompleteOrder`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/orders/{id}/complete
	CompleteOrder(ctx context.Context, req *CompleteOrderRequest, params CompleteOrderParams) (CompleteOrderRes, error)
	// CreateApiKey implements createApiKey operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ApiKeyHandler).Create`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/api-keys
	CreateApiKey(ctx context.Context, req *CreateApiKeyInput, params CreateApiKeyParams) (CreateApiKeyRes, error)
	// CreateCoupon implements createCoupon operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*CouponHandler).Create`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/coupons
	CreateCoupon(ctx context.Context, req *CreateCouponInput, params CreateCouponParams) (CreateCouponRes, error)
	// CreateCouponCode implements createCouponCode operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*CouponHandler).CreateCode`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/coupons/{id}/codes
	CreateCouponCode(ctx context.Context, req *CreateCouponCodeInput, params CreateCouponCodeParams) (CreateCouponCodeRes, error)
	// CreateCustomer implements createCustomer operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*CustomerHandler).Create`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/customers
	CreateCustomer(ctx context.Context, req *CreateCustomerInput, params CreateCustomerParams) (CreateCustomerRes, error)
	// CreateCustomerPaymentMethod implements createCustomerPaymentMethod operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*CustomerHandler).CreateCustomerPaymentMethod`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/customers/{id}/payment-methods
	CreateCustomerPaymentMethod(ctx context.Context, req CreatePaymentMethodInput, params CreateCustomerPaymentMethodParams) (CreateCustomerPaymentMethodRes, error)
	// CreateDunningConfiguration implements createDunningConfiguration operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*DunningHandler).CreateConfiguration`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/dunning/configurations
	CreateDunningConfiguration(ctx context.Context, req *CreateDunningConfigurationRequest, params CreateDunningConfigurationParams) (CreateDunningConfigurationRes, error)
	// CreateGateway implements createGateway operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*PspHandler).Create`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/gateways
	CreateGateway(ctx context.Context, req *CreateGatewayRequest, params CreateGatewayParams) (CreateGatewayRes, error)
	// CreateMeter implements createMeter operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*MeterHandler).Create`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/meters
	CreateMeter(ctx context.Context, req *CreateMeterRequest, params CreateMeterParams) (CreateMeterRes, error)
	// CreateOrder implements createOrder operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*OrderHandler).CreateOrder`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/orders
	CreateOrder(ctx context.Context, req *CreateOrderRequest, params CreateOrderParams) (CreateOrderRes, error)
	// CreateOrganization implements createOrganization operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*OrgHandler).Create`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/organizations
	CreateOrganization(ctx context.Context, req *CreateOrgRequest, params CreateOrganizationParams) (CreateOrganizationRes, error)
	// CreatePaymentToken implements createPaymentToken operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*DunningHandler).CreatePaymentToken`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/admin/subscriptions/{id}/payment-tokens
	CreatePaymentToken(ctx context.Context, req *CreatePaymentTokenRequest, params CreatePaymentTokenParams) (CreatePaymentTokenRes, error)
	// CreatePrice implements createPrice operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).CreatePrice`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/prices
	CreatePrice(ctx context.Context, req *CreatePriceRequest, params CreatePriceParams) (CreatePriceRes, error)
	// CreateProduct implements createProduct operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).Create`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/products
	CreateProduct(ctx context.Context, req *CreateProductRequest, params CreateProductParams) (CreateProductRes, error)
	// CreateProductVariant implements createProductVariant operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).CreateVariant`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/products/{id}/variants
	CreateProductVariant(ctx context.Context, req *CreateVariantRequest, params CreateProductVariantParams) (CreateProductVariantRes, error)
	// CreateSession implements createSession operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*SessionHandler).Create`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/sessions
	CreateSession(ctx context.Context, req *CreateSessionRequest, params CreateSessionParams) (CreateSessionRes, error)
	// CreateSetting implements createSetting operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*SettingHandler).Create`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/settings
	CreateSetting(ctx context.Context, req *CreateSettingRequest, params CreateSettingParams) (CreateSettingRes, error)
	// CreateWebhookSubscription implements createWebhookSubscription operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*WebhookSubscriptionHandler).Create`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/webhooks
	CreateWebhookSubscription(ctx context.Context, req *CreateWebhookSubscriptionRequest, params CreateWebhookSubscriptionParams) (CreateWebhookSubscriptionRes, error)
	// DeleteApiKey implements deleteApiKey operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ApiKeyHandler).Delete`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// DELETE /api/api-keys/{id}
	DeleteApiKey(ctx context.Context, params DeleteApiKeyParams) (DeleteApiKeyRes, error)
	// DeleteCoupon implements deleteCoupon operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*CouponHandler).Delete`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// DELETE /api/coupons/{id}
	DeleteCoupon(ctx context.Context, params DeleteCouponParams) (DeleteCouponRes, error)
	// DeletePrice implements deletePrice operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).DeletePrice`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// DELETE /api/prices/{priceId}
	DeletePrice(ctx context.Context, params DeletePriceParams) (DeletePriceRes, error)
	// DeleteProduct implements deleteProduct operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).Delete`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// DELETE /api/products/{id}
	DeleteProduct(ctx context.Context, params DeleteProductParams) (DeleteProductRes, error)
	// DeleteSetting implements deleteSetting operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*SettingHandler).Delete`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// DELETE /api/settings/{parentId}/{id}
	DeleteSetting(ctx context.Context, params DeleteSettingParams) (DeleteSettingRes, error)
	// DeleteVariant implements deleteVariant operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).DeleteVariant`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// DELETE /api/variants/{variantId}
	DeleteVariant(ctx context.Context, params DeleteVariantParams) (DeleteVariantRes, error)
	// GetCoupon implements getCoupon operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*CouponHandler).Get`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/coupons/{id}
	GetCoupon(ctx context.Context, params GetCouponParams) (GetCouponRes, error)
	// GetCustomer implements getCustomer operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*CustomerHandler).Get`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/customers/{id}
	GetCustomer(ctx context.Context, params GetCustomerParams) (GetCustomerRes, error)
	// GetCustomerDunningHistory implements getCustomerDunningHistory operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*DunningHandler).GetCustomerDunningHistory`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/customers/{id}/dunning-history
	GetCustomerDunningHistory(ctx context.Context, params GetCustomerDunningHistoryParams) (GetCustomerDunningHistoryRes, error)
	// GetDiscount implements getDiscount operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*CouponHandler).GetDiscount`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/discounts/{id}
	GetDiscount(ctx context.Context, params GetDiscountParams) (GetDiscountRes, error)
	// GetDunningCampaign implements getDunningCampaign operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*DunningHandler).GetCampaign`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/dunning/campaigns/{id}
	GetDunningCampaign(ctx context.Context, params GetDunningCampaignParams) (GetDunningCampaignRes, error)
	// GetDunningConfiguration implements getDunningConfiguration operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*DunningHandler).GetConfiguration`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/dunning/configurations/{id}
	GetDunningConfiguration(ctx context.Context, params GetDunningConfigurationParams) (GetDunningConfigurationRes, error)
	// GetHealth implements getHealth operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*HealthHandler).Healthcheck`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/health
	GetHealth(ctx context.Context, params GetHealthParams) (GetHealthRes, error)
	// GetInvoice implements getInvoice operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*InvoiceHandler).Get`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/invoices/{id}
	GetInvoice(ctx context.Context, params GetInvoiceParams) (GetInvoiceRes, error)
	// GetMeter implements getMeter operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*MeterHandler).Get`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/meters/{id}
	GetMeter(ctx context.Context, params GetMeterParams) (GetMeterRes, error)
	// GetOrder implements getOrder operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*OrderHandler).Get`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/orders/{id}
	GetOrder(ctx context.Context, params GetOrderParams) (GetOrderRes, error)
	// GetPayment implements getPayment operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*PaymentHandler).Get`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/payments/{id}
	GetPayment(ctx context.Context, params GetPaymentParams) (GetPaymentRes, error)
	// GetPaymentMethod implements getPaymentMethod operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*PaymentMethodHandler).Get`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/payment-methods/{id}
	GetPaymentMethod(ctx context.Context, params GetPaymentMethodParams) (GetPaymentMethodRes, error)
	// GetPrice implements getPrice operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).GetPrice`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/prices/{priceId}
	GetPrice(ctx context.Context, params GetPriceParams) (GetPriceRes, error)
	// GetProduct implements getProduct operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).Get`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/products/{id}
	GetProduct(ctx context.Context, params GetProductParams) (GetProductRes, error)
	// GetReminderConfig implements getReminderConfig operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ReminderConfigHandler).Get`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/billing/reminder-config
	GetReminderConfig(ctx context.Context, params GetReminderConfigParams) (GetReminderConfigRes, error)
	// GetSetting implements getSetting operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*SettingHandler).Get`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/settings/{parentId}/{id}
	GetSetting(ctx context.Context, params GetSettingParams) (GetSettingRes, error)
	// GetSubscription implements getSubscription operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*SubscriptionHandler).Get`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/subscriptions/{id}
	GetSubscription(ctx context.Context, params GetSubscriptionParams) (GetSubscriptionRes, error)
	// GetSubscriptionUsage implements getSubscriptionUsage operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*UsageHandler).SubscriptionUsage`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/subscriptions/{id}/usage
	GetSubscriptionUsage(ctx context.Context, params GetSubscriptionUsageParams) (GetSubscriptionUsageRes, error)
	// GetVariant implements getVariant operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).GetVariant`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/variants/{variantId}
	GetVariant(ctx context.Context, params GetVariantParams) (GetVariantRes, error)
	// IngestUsageEvents implements ingestUsageEvents operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*UsageHandler).Ingest`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/usage/ingest
	IngestUsageEvents(ctx context.Context, req *IngestEventsRequest, params IngestUsageEventsParams) (IngestUsageEventsRes, error)
	// ListApiKeys implements listApiKeys operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ApiKeyHandler).List`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/api-keys
	ListApiKeys(ctx context.Context, params ListApiKeysParams) (ListApiKeysRes, error)
	// ListCouponCodes implements listCouponCodes operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*CouponHandler).ListCodes`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/coupons/{id}/codes
	ListCouponCodes(ctx context.Context, params ListCouponCodesParams) (ListCouponCodesRes, error)
	// ListCoupons implements listCoupons operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*CouponHandler).List`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/coupons
	ListCoupons(ctx context.Context, params ListCouponsParams) (ListCouponsRes, error)
	// ListCustomers implements listCustomers operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*CustomerHandler).List`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/customers
	ListCustomers(ctx context.Context, params ListCustomersParams) (ListCustomersRes, error)
	// ListDunningCampaignAttempts implements listDunningCampaignAttempts operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*DunningHandler).ListCampaignAttempts`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/dunning/campaigns/{id}/attempts
	ListDunningCampaignAttempts(ctx context.Context, params ListDunningCampaignAttemptsParams) (ListDunningCampaignAttemptsRes, error)
	// ListDunningCampaignCommunications implements listDunningCampaignCommunications operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*DunningHandler).ListCampaignCommunications`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/dunning/campaigns/{id}/communications
	ListDunningCampaignCommunications(ctx context.Context, params ListDunningCampaignCommunicationsParams) (ListDunningCampaignCommunicationsRes, error)
	// ListDunningCampaigns implements listDunningCampaigns operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*DunningHandler).ListCampaigns`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/dunning/campaigns
	ListDunningCampaigns(ctx context.Context, params ListDunningCampaignsParams) (ListDunningCampaignsRes, error)
	// ListDunningConfigurations implements listDunningConfigurations operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*DunningHandler).ListConfigurations`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/dunning/configurations
	ListDunningConfigurations(ctx context.Context, params ListDunningConfigurationsParams) (ListDunningConfigurationsRes, error)
	// ListInvoices implements listInvoices operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*InvoiceHandler).List`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/invoices
	ListInvoices(ctx context.Context, params ListInvoicesParams) (ListInvoicesRes, error)
	// ListMeters implements listMeters operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*MeterHandler).List`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/meters
	ListMeters(ctx context.Context, params ListMetersParams) (ListMetersRes, error)
	// ListOrderSubscriptions implements listOrderSubscriptions operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*OrderHandler).ListSubscriptions`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/orders/{id}/subscriptions
	ListOrderSubscriptions(ctx context.Context, params ListOrderSubscriptionsParams) (ListOrderSubscriptionsRes, error)
	// ListOrders implements listOrders operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*OrderHandler).List`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/orders
	ListOrders(ctx context.Context, params ListOrdersParams) (ListOrdersRes, error)
	// ListPayments implements listPayments operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*PaymentHandler).List`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/payments
	ListPayments(ctx context.Context, params ListPaymentsParams) (ListPaymentsRes, error)
	// ListProductVariants implements listProductVariants operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).ListVariants`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/products/{id}/variants
	ListProductVariants(ctx context.Context, params ListProductVariantsParams) (ListProductVariantsRes, error)
	// ListProducts implements listProducts operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).List`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/products
	ListProducts(ctx context.Context, params ListProductsParams) (ListProductsRes, error)
	// ListSettings implements listSettings operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*SettingHandler).List`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/settings
	ListSettings(ctx context.Context, params ListSettingsParams) (ListSettingsRes, error)
	// ListSubscriptionInvoices implements listSubscriptionInvoices operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*InvoiceHandler).ListBySubscription`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/subscriptions/{id}/invoices
	ListSubscriptionInvoices(ctx context.Context, params ListSubscriptionInvoicesParams) (ListSubscriptionInvoicesRes, error)
	// ListSubscriptionPayments implements listSubscriptionPayments operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*SubscriptionHandler).ListPayments`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/subscriptions/{id}/payments
	ListSubscriptionPayments(ctx context.Context, params ListSubscriptionPaymentsParams) (ListSubscriptionPaymentsRes, error)
	// ListSubscriptions implements listSubscriptions operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*SubscriptionHandler).List`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/subscriptions
	ListSubscriptions(ctx context.Context, params ListSubscriptionsParams) (ListSubscriptionsRes, error)
	// ListVariantPrices implements listVariantPrices operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).ListPrices`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/variants/{variantId}/prices
	ListVariantPrices(ctx context.Context, params ListVariantPricesParams) (ListVariantPricesRes, error)
	// ListWebhookSubscriptions implements listWebhookSubscriptions operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*WebhookSubscriptionHandler).List`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// GET /api/webhooks
	ListWebhookSubscriptions(ctx context.Context, params ListWebhookSubscriptionsParams) (ListWebhookSubscriptionsRes, error)
	// PauseSubscription implements pauseSubscription operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*SubscriptionHandler).Pause`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// PUT /api/subscriptions/{id}/pause
	PauseSubscription(ctx context.Context, req *PauseSubscriptionRequest, params PauseSubscriptionParams) (PauseSubscriptionRes, error)
	// ReceiveWebhook implements receiveWebhook operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*WebhookHandler).Process`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/notify
	ReceiveWebhook(ctx context.Context, params ReceiveWebhookParams) (ReceiveWebhookRes, error)
	// RemoveItemFromCart implements removeItemFromCart operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*CartHandler).RemoveItem`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/carts/{id}/remove
	RemoveItemFromCart(ctx context.Context, req *RemoveItemRequest, params RemoveItemFromCartParams) (RemoveItemFromCartRes, error)
	// ResumeSubscription implements resumeSubscription operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*SubscriptionHandler).Resume`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// PUT /api/subscriptions/{id}/resume
	ResumeSubscription(ctx context.Context, req *ResumeSubscriptionRequest, params ResumeSubscriptionParams) (ResumeSubscriptionRes, error)
	// TriggerDunningManualAttempt implements triggerDunningManualAttempt operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*DunningHandler).TriggerManualAttempt`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/dunning/campaigns/{id}/attempts
	TriggerDunningManualAttempt(ctx context.Context, req *TriggerManualAttemptRequest, params TriggerDunningManualAttemptParams) (TriggerDunningManualAttemptRes, error)
	// UnarchiveProduct implements unarchiveProduct operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).Unarchive`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/products/{id}/unarchive
	UnarchiveProduct(ctx context.Context, params UnarchiveProductParams) (UnarchiveProductRes, error)
	// UpdateCoupon implements updateCoupon operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*CouponHandler).Update`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// PATCH /api/coupons/{id}
	UpdateCoupon(ctx context.Context, req *UpdateCouponInput, params UpdateCouponParams) (UpdateCouponRes, error)
	// UpdateCouponCode implements updateCouponCode operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*CouponHandler).UpdateCode`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// PATCH /api/coupon-codes/{id}
	UpdateCouponCode(ctx context.Context, req *UpdateCouponCodeInput, params UpdateCouponCodeParams) (UpdateCouponCodeRes, error)
	// UpdateCustomerPaymentMethod implements updateCustomerPaymentMethod operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*CustomerHandler).UpdateCustomerPaymentMethod`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// PUT /api/customers/{id}/payment-methods/{pmid}
	UpdateCustomerPaymentMethod(ctx context.Context, req UpdatePaymentMethodInput, params UpdateCustomerPaymentMethodParams) (UpdateCustomerPaymentMethodRes, error)
	// UpdateDunningCampaign implements updateDunningCampaign operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*DunningHandler).UpdateCampaign`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// PATCH /api/dunning/campaigns/{id}
	UpdateDunningCampaign(ctx context.Context, req *UpdateDunningCampaignRequest, params UpdateDunningCampaignParams) (UpdateDunningCampaignRes, error)
	// UpdateDunningConfiguration implements updateDunningConfiguration operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*DunningHandler).UpdateConfiguration`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// PATCH /api/dunning/configurations/{id}
	UpdateDunningConfiguration(ctx context.Context, req *UpdateDunningConfigurationRequest, params UpdateDunningConfigurationParams) (UpdateDunningConfigurationRes, error)
	// UpdatePrice implements updatePrice operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).UpdatePrice`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// PATCH /api/prices/{priceId}
	UpdatePrice(ctx context.Context, req *CreatePriceRequest, params UpdatePriceParams) (UpdatePriceRes, error)
	// UpdateProduct implements updateProduct operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).Update`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// PATCH /api/products/{id}
	UpdateProduct(ctx context.Context, req *UpdateProductRequest, params UpdateProductParams) (UpdateProductRes, error)
	// UpdateReminderConfig implements updateReminderConfig operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ReminderConfigHandler).Put`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// PUT /api/billing/reminder-config
	UpdateReminderConfig(ctx context.Context, req *ReminderConfigDTO, params UpdateReminderConfigParams) (UpdateReminderConfigRes, error)
	// UpdateSetting implements updateSetting operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*SettingHandler).Update`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// PUT /api/settings/{parentId}/{id}
	UpdateSetting(ctx context.Context, req *UpdateSettingRequest, params UpdateSettingParams) (UpdateSettingRes, error)
	// UpdateSubscription implements updateSubscription operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*SubscriptionHandler).Update`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// PATCH /api/subscriptions/{id}
	UpdateSubscription(ctx context.Context, req *UpdateSubscriptionRequest, params UpdateSubscriptionParams) (UpdateSubscriptionRes, error)
	// UpdateSubscriptionBillingAnchor implements updateSubscriptionBillingAnchor operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*SubscriptionHandler).UpdateBillingAnchor`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// PATCH /api/subscriptions/{id}/billing-anchor
	UpdateSubscriptionBillingAnchor(ctx context.Context, req *UpdateBillingAnchorRequest, params UpdateSubscriptionBillingAnchorParams) (UpdateSubscriptionBillingAnchorRes, error)
	// UpdateVariant implements updateVariant operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*ProductHandler).UpdateVariant`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// PUT /api/variants/{variantId}
	UpdateVariant(ctx context.Context, req *UpdateVariantRequest, params UpdateVariantParams) (UpdateVariantRes, error)
	// VerifyPaymentToken implements verifyPaymentToken operation.
	//
	// # Controller:
	//
	// `getpaidhq/internal/adapter/http.(*DunningHandler).VerifyPaymentToken`
	//
	// # Middlewares:
	//
	//  - `github.com/go-fuego/fuego.defaultLogger.middleware`
	//
	// POST /api/payment-tokens/verify
	VerifyPaymentToken(ctx context.Context, req *VerifyPaymentTokenRequest, params VerifyPaymentTokenParams) (VerifyPaymentTokenRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
