services:
  payloop_pg:
    container_name: payloop_pg
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/data/postgres

volumes:
  pg_data:
