services:
  mm_pg:
    container_name: mm_pg
    image: postgres:latest
    ports:
      - '6432:5432'
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/data/postgres

volumes:
  pg_data:
